runtime: python
env: flex
entrypoint: rcloadenv dpebot -- gunicorn -c gunicorn.conf.py -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  # Required for requests to be able to verify googleapis.com certificates.
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

# https://cloud.google.com/appengine/docs/flexible/python/migrating-to-split-health-checks
#featureSettings:
#  splitHealthChecks: true

liveness_check:
  path: "/"

readiness_check:
  path: "/"
