name: CI Tests

on:
  - pull_request
  - push

env:
  CI: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Scripts
        run: ./check.sh
